version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build Docker image
          command: docker build -t mohitsoniv/myapp-devops-starter:latest .
      - run:
          name: Log in to DockerHub
          command: echo $DOCKERHUB_TOKEN | docker login -u mohitsoniv --password-stdin
      - run:
          name: Push image
          command: docker push mohitsoniv/myapp-devops-starter:latest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
