  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: myapp-deployment
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: myapp
    template:
      metadata:
        labels:
          app: myapp
      spec:
        containers:
        - name: myapp
          image: mohitsoniv/myapp-devops-starter:latest
          ports:
          - containerPort: 3000
          env:
          - name: NODE_ENV
            value: "production"
          - name: DD_SERVICE
            value: "myapp"
          - name: DD_ENV
            value: "prod"
          - name: DD_VERSION
            value: "1.0.0"
          - name: BUGSNAG_API_KEY
            valueFrom:
              secretKeyRef:
                name: myapp-secrets
                key: BUGSNAG_API_KEY
---
  apiVersion: v1
  kind: Service
  metadata:
    name: myapp-service
  spec:
    selector:
      app: myapp
    ports:
      - protocol: TCP
        port: 80
        targetPort: 3000
    type: LoadBalancer
