  apiVersion: v1
  kind: Namespace
  metadata:
    name: myapp
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: myapp-deployment
    namespace: myapp
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: myapp
    template:
      metadata:
        labels:
          app: myapp
      spec:
        containers:
          - name: myapp
            image: DOCKERHUB_USERNAME/myapp-devops-starter:latest
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 3000
            env:
              - name: NODE_ENV
                value: "production"
              - name: BUGSNAG_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: myapp-secrets
                    key: BUGSNAG_API_KEY
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "256Mi"
        imagePullSecrets: []
---
  apiVersion: v1
  kind: Service
  metadata:
    name: myapp-service
    namespace: myapp
  spec:
    selector:
      app: myapp
    ports:
      - port: 80
        targetPort: 3000
    type: LoadBalancer
