name: CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t mohitsoniv/myapp-devops-starter:latest .

      - name: Log in to DockerHub
        run: echo "dckr_pat_xzIQRVqKp60J1bwZYQIbR4dCnv0" | docker login -u "mohitsoniv" --password-stdin

      - name: Push image
        run: docker push mohitsoniv/myapp-devops-starter:latest
